# Generated by Django 3.1.3 on 2020-12-28 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_like_post_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 12, 16, 30, 809151)),
        ),
    ]
